export const FETCH_ALL_BREEDS = 'FETCH_ALL_BREEDS';
export const FETCH_PUGS = 'FETCH_PUGS';
export const CHOOSE_BREED = 'CHOOSE_BREED';
export const AUTHENTICATED = 'AUTHENTICATED';
export const USER = 'USER';
export const AUTHENTICATING = 'AUTHENTICATING';